name: "\U0001F41B Bug report"
description: "Let us know if something is wrong \U0001F914"
title: "\U0001F41B "
labels: [bug, needs triage]
body:
- type: markdown
  attributes:
    value: |
      Make sure to add all the information needed to understand the bug so that someone can help. If the info is missing we'll add the `Needs more information` label and close the issue until there is enough information.
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: It would greatly help us reduce duplicates and we would really appreciate it if you could search the existing issues for the problem you are experiencing.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  id: current_behavior
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  id: repro_steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behaviour. If the error came in a response from the REST API, please specify the URL here.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    id: system_env
    label: Environment
    description: |
      If you have used the public API, please just say "Used public API", and add your browser and its version.
      If you are self-hosting, then write down your OS, the method of hosting (docker/container, Kubernetes, or plain), and the version of Jikan you are running.
      examples:
        - **OS**: Ubuntu 20.04
        - **Browser**: Firefox 104.1
        - **Android Runtime**: 7.6.3
    placeholder: |
        - OS:
        - Browser:
        - PHP Version on the server side (if self-hosted):
        - Is Redis used (if self-hosted):
        - Search engine used (if self-hosted):
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    id: extra_info
    label: Anything else?
    description: |
      Other information / Contextual information. Links? References? Anything that will give us more context about the issue you are encountering!
      e.g. detailed explanation, stack traces, related issues, screenshots, suggestions on how to fix, links for us to have context, eg. stackoverflow, discord channel link, etc

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
